name: ESP32-Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '90 seconds'
          skip-recent: 1      
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build ESP32 firmware
        run: pio run -d firmware/ESP32/
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: esp32-firmware
          path: |
            firmware/ESP32/.pio/build/esp32dev/firmware.bin
            firmware/ESP32/.pio/build/esp32dev/partitions.bin
            firmware/ESP32/.pio/build/esp32dev/bootloader.bin