name: Github-Page-Deployment

on: [ push ]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '90 seconds'
          skip-recent: 5
      - name: Prepare and checkout   
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - uses: actions/checkout@v3
      - name: GH-Page Build
        working-directory: ./headless_haystack
        run: |
          ls -al
          flutter pub get
          flutter build web --release --base-href "/headless-haystack/"
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./headless_haystack/build/web